### ISSUE TITLE
Array to string conversion on product edit page

### ISSUE THREAD

**Issue by bery** [avstudnitz/AvS_ScopeHint2#13]
Hi,

I have found a bug on a product edit page in the backend.
Reproduction steps:

1. Open product edit page in Magento admin
2. Open advanced pricing
3. Fill tier prices

**Actual result**
1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /var/www/html/vendor/avstudnitz/scopehint2/Plugin/ProductEavDataProviderPlugin.php on line 76

**Expected result**
A product is saved and no exception is thrown

![image](https://user-images.githubusercontent.com/1456931/53482904-94e87d00-3a80-11e9-9b2c-25517aaa8ea4.png)

**Comment by seansan** [comment]
A quick workaround would be to add a try / catch statement ... or implode an array
