### ISSUE TITLE
Re-ordering of modules in config.php

### ISSUE THREAD

**Issue by leek** [avstudnitz/AvS_ScopeHint2#3]
We were experiencing this issue:
https://github.com/magento/magento2/issues/12405

And noticed with AvS_ScopeHint2 installed, `Magento_Config` was always higher than `Magento_Store` after running `setup:upgrade`. We were unable to create new websites or stores.

After removing AvS_ScopeHint2 and running `setup:upgrade`, our `config.php` module ordering corrected itself and all previous errors when creating websites/stores was fixed.

I'm sorry that I can't provide much more information than that - but unfortunately, this module is unusable for us because of the negative side effects I've mentioned.

**Comment by seansan** [comment]
Maybe close? seems the upstream issue magento/magento2#12405 was fixed
