### ISSUE TITLE
Comments not translated

### ISSUE THREAD

**Issue by a-leurs** [avstudnitz/AvS_ScopeHint2#33]
The method `\AvS\ScopeHint\Plugin\ConfigFieldPlugin::afterGetComment()` adds the configuration code to each comment.

Problem then is that the strings aren't translated anymore.

For example when I have a the comment `Enables or disables Payment Reminder module.` for a label in my custom module, and a translation text in my i18n/de_DE.csv then the afterGetComment() method changes the comment to `Enables or disables Payment Reminder module. <br />Path: <code>path/to/comment</code>` and that can't be translated anymore.

**Comment by schmengler** [comment]
Potential fix in https://github.com/avstudnitz/AvS_ScopeHint2/blob/master/Plugin/ConfigFieldPlugin.php#L93-L94

if the result is **not** a `Phrase` object (i.e. not translated text yet), turn it into one using `$result = __($result)`, then continue.

What do you think @avstudnitz ? Good first issue for a PR? :wink:

**Comment by schmengler** [comment]
apparently there's already a PR: #23 (seems to work too, although the code is more complicated than needed)

**Comment by NathanDayFE** [comment]
On the back of the fix #34, this module is now not compatible with `Magento_SharedCatalog` or at least in the latest version of that module, I haven't looked at previous versions. Obviously this isn't a module that comes with Open Source, so can understand why it hasn't been picked up.

Specifically the `\Magento\SharedCatalog\Block\Adminhtml\System\Config\WebsiteRestriction\IsActive::prepareComment` function
```PHP
    /**
     * Prepare element comment
     *
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element
     * @return void
     */
    protected function prepareComment(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        if (!$element->getComment()) {
            return;
        }

        if (false && $this->isPublicCatalogExist()) {
            $element->unsComment();
        } else {
            $comment = new Phrase($element->getComment()->getText(), [$this->getCatalogCreateUrl()]);
            $element->setComment($comment);
        }
    }
```

This function expects the comment to be a phrase, however it is now just a string

When a phrase is appended to a string as it does on https://github.com/avstudnitz/AvS_ScopeHint2/blob/master/Plugin/ConfigFieldPlugin.php#L102 it is implicitly cast to a string.

We could get around this with

```PHP
    /**
     * @param Subject $subject
     * @param string $result
     * @return string
     */
    public function afterGetComment(Subject $subject, $result)
    {
        $phrase = false;

        if ($result instanceof Phrase) {
            $phrase = true;
            $result = (string) $result;
        }

        if (strlen(trim($result))) {
            $result .= '<br />';
        }

        $result .= __('Path: <code>%1</code>', $this->getPath($subject));

        return $phrase? __($result) : $result;
    }
 ```

**Comment by NathanDayFE** [comment]
Actually, on second thought's that won't work as the `PrepareComment` functions expects to receive the untranslated phrase to re-insert a different variable. will have to determine an alternative solution

**Comment by lefte** [comment]
I commented in PR #35 about the specific steps I used to to resolve my issue with Magento management for Adobe Commerce (aka Enterprise Edition) and an error about Phrase being getText() as a string.
