### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by woutk88** [avstudnitz/AvS_ScopeHint2#7]
Dear developer,

Can you please make sure packagist is also getting updated with the latest versions? I now need to add this repository to my composer.json in order to install the Magento 2.3 compatible version.

**Comment by ThomasNegeli** [comment]
@avstudnitz 
could you please just remove this line here: https://github.com/avstudnitz/AvS_ScopeHint2/blob/master/composer.json#L8
If you use git tags for releases, this string will override your tag. And in the current case you missed to raise the version for the new release.
https://getcomposer.org/doc/02-libraries.md#library-versioning

**Comment by Axel29** [comment]
A temporary fix would be to use `composer require avstudnitz/scopehint2:dev-master` to install it since it requires magento/framework: ~100.0|~101.0|~102.0 which is fine.

**Comment by avstudnitz** [comment]
It's merged, and a new release has been created and promoted to packagist. Thanks for your patience.

**Comment by Axel29** [comment]
Great thanks.
